# Generated by Django 5.2.14 on 2026-05-18 07:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("descriptif", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Catégories",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("numero_client", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("date_inscription", models.DateField()),
                ("adresse", models.TextField()),
            ],
            options={
                "db_table": "clients",
            },
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "numero_commande",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date_commande", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        db_column="client_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drive.client",
                    ),
                ),
            ],
            options={
                "db_table": "commandes",
            },
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=150)),
                ("date_peremption", models.DateField(blank=True, null=True)),
                ("photo", models.CharField(blank=True, max_length=255, null=True)),
                ("marque", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "prix",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        db_column="categorie_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drive.categorie",
                    ),
                ),
            ],
            options={
                "db_table": "produits",
            },
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantite",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        db_column="commande_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drive.commande",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        db_column="produit_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drive.produit",
                    ),
                ),
            ],
            options={
                "db_table": "lignes_commande",
            },
        ),
    ]
